services:
  backend:
    env_file:
      - ./envs/local/.env.app
    restart: unless-stopped

  db:
    env_file:
      - ./envs/local/.env.db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped

networks:
  app:
    internal: false
  db:
    internal: true
